//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogla()
        {
            this.ProfilAplikantas = new HashSet<ProfilAplikanta>();
        }
    
        public int Id { get; set; }
        public string RadnoMjesto { get; set; }
        public string DodatneInformacije { get; set; }
        public int PocetakPrijave { get; set; }
        public int DatumIsteka { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ProfilKompanijeId { get; set; }
    
        public virtual ProfilKompanije ProfilKompanije { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilAplikanta> ProfilAplikantas { get; set; }
    }
}
