//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilKompanije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfilKompanije()
        {
            this.Oglas = new HashSet<Ogla>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Misija { get; set; }
        public string Logo { get; set; }
        public string Email { get; set; }
        public string KontaktTelefon { get; set; }
        public string WebSiteURL { get; set; }
        public Nullable<int> AdresaId { get; set; }
    
        public virtual AdresaKompanije AdresaKompanije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogla> Oglas { get; set; }
    }
}
