//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadnoIskustvo
    {
        public int Id { get; set; }
        public string NazivKompanije { get; set; }
        public string Adresa { get; set; }
        public string RadnaPozicija { get; set; }
        public int DatumPocetka { get; set; }
        public int DatumZavrsetka { get; set; }
        public Nullable<int> ProfilAplikantaId { get; set; }
    
        public virtual ProfilAplikanta ProfilAplikanta { get; set; }
    }
}
