//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vjestine
    {
        public int Id { get; set; }
        public string Vjestina { get; set; }
        public string NivoPoznavanja { get; set; }
        public Nullable<int> ProfilAplikantaId { get; set; }
    
        public virtual ProfilAplikanta ProfilAplikanta { get; set; }
    }
}
